# Generated by Django 4.0.6 on 2022-08-01 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
    ]
